// Generated by scripts/generate_dashboard.py; do not edit.
window.HEALTH_DIARY_DATA = {
  "meta": {
    "months": [
      "2026-08"
    ],
    "latest_date": "2026-08-08"
  },
  "daily": [
    {
      "diary_date": "2026-08-04",
      "status": "complete",
      "calories_kcal": 2225.0,
      "protein_g": 118.5,
      "fat_g": 104.5,
      "carbs_g": 123.5,
      "workout_count": 1,
      "workout_minutes": 30.0,
      "distance_km": 5.15,
      "sleep_minutes": 330,
      "sleep_quality": null,
      "food_bases": "chicken, fish",
      "day_rating": 4,
      "expenses_rub": 2050.0,
      "nutrition_entry_count": 4,
      "meal_type_count": 4,
      "has_sleep": 1,
      "has_workout": 1,
      "has_rating": 1,
      "has_expenses": 1
    },
    {
      "diary_date": "2026-08-05",
      "status": "complete",
      "calories_kcal": 2353.6,
      "protein_g": 142.6,
      "fat_g": 112.9,
      "carbs_g": 172.1,
      "workout_count": 1,
      "workout_minutes": 48.0,
      "distance_km": 0.0,
      "sleep_minutes": 300,
      "sleep_quality": null,
      "food_bases": "chicken, fish",
      "day_rating": 4,
      "expenses_rub": 430.0,
      "nutrition_entry_count": 4,
      "meal_type_count": 4,
      "has_sleep": 1,
      "has_workout": 1,
      "has_rating": 1,
      "has_expenses": 1
    },
    {
      "diary_date": "2026-08-06",
      "status": "complete",
      "calories_kcal": 1955.0,
      "protein_g": 115.0,
      "fat_g": 66.9,
      "carbs_g": 229.8,
      "workout_count": 1,
      "workout_minutes": 30.0,
      "distance_km": 5.52,
      "sleep_minutes": 360,
      "sleep_quality": null,
      "food_bases": "chicken, fish",
      "day_rating": 4,
      "expenses_rub": 0.0,
      "nutrition_entry_count": 6,
      "meal_type_count": 4,
      "has_sleep": 1,
      "has_workout": 1,
      "has_rating": 1,
      "has_expenses": 1
    },
    {
      "diary_date": "2026-08-07",
      "status": "complete",
      "calories_kcal": 1630.0,
      "protein_g": 91.4,
      "fat_g": 59.7,
      "carbs_g": 197.0,
      "workout_count": 1,
      "workout_minutes": 31.0,
      "distance_km": 5.7,
      "sleep_minutes": 330,
      "sleep_quality": null,
      "food_bases": "chicken, fish",
      "day_rating": 5,
      "expenses_rub": 0.0,
      "nutrition_entry_count": 7,
      "meal_type_count": 4,
      "has_sleep": 1,
      "has_workout": 1,
      "has_rating": 1,
      "has_expenses": 0
    },
    {
      "diary_date": "2026-08-08",
      "status": "in_progress",
      "calories_kcal": 771.0,
      "protein_g": 50.8,
      "fat_g": 37.5,
      "carbs_g": 58.3,
      "workout_count": 0,
      "workout_minutes": 0.0,
      "distance_km": 0.0,
      "sleep_minutes": 510,
      "sleep_quality": null,
      "food_bases": "fish",
      "day_rating": null,
      "expenses_rub": 0.0,
      "nutrition_entry_count": 2,
      "meal_type_count": 1,
      "has_sleep": 1,
      "has_workout": 0,
      "has_rating": 0,
      "has_expenses": 0
    }
  ],
  "meals": [
    {
      "diary_date": "2026-08-04",
      "meal_type": "breakfast",
      "calories_kcal": 610.0,
      "protein_g": 35.0,
      "fat_g": 28.0,
      "carbs_g": 61.0,
      "foods": "2 яйца; блинчик с курицей; овощной салат; банан; чай"
    },
    {
      "diary_date": "2026-08-04",
      "meal_type": "dinner",
      "calories_kcal": 600.0,
      "protein_g": 46.0,
      "fat_g": 34.0,
      "carbs_g": 22.5,
      "foods": "Лосось; стручковая фасоль; салат с помидорами, огурцами, оливками и рукколой"
    },
    {
      "diary_date": "2026-08-04",
      "meal_type": "lunch",
      "calories_kcal": 825.0,
      "protein_g": 37.5,
      "fat_g": 42.5,
      "carbs_g": 40.0,
      "foods": "Салат с баклажанами, помидорами и зеленью; соба с овощами; котлета по-киевски"
    },
    {
      "diary_date": "2026-08-04",
      "meal_type": "snack",
      "calories_kcal": 190.0,
      "protein_g": 0.0,
      "fat_g": 0.0,
      "carbs_g": 0.0,
      "foods": "2 яблока"
    },
    {
      "diary_date": "2026-08-05",
      "meal_type": "breakfast",
      "calories_kcal": 753.0,
      "protein_g": 31.8,
      "fat_g": 36.3,
      "carbs_g": 50.6,
      "foods": "Яичница из 1 яйца; салат из помидоров, огурцов и перца; скрэмбл со шпинатом и томатами; блинчик с яблоком; 2 мини-сосиски молочные"
    },
    {
      "diary_date": "2026-08-05",
      "meal_type": "dinner",
      "calories_kcal": 595.0,
      "protein_g": 62.3,
      "fat_g": 33.1,
      "carbs_g": 9.8,
      "foods": "Обжаренное филе; сыр маасдам; руккола с песто; томаты; зелёные оливки"
    },
    {
      "diary_date": "2026-08-05",
      "meal_type": "lunch",
      "calories_kcal": 743.6,
      "protein_g": 45.2,
      "fat_g": 42.3,
      "carbs_g": 44.7,
      "foods": "Сливочный рыбный суп; паста с курицей и шампиньонами; салат «Венеция»"
    },
    {
      "diary_date": "2026-08-05",
      "meal_type": "snack",
      "calories_kcal": 262.0,
      "protein_g": 3.3,
      "fat_g": 1.2,
      "carbs_g": 67.0,
      "foods": "Яблоко; банан; нектарин"
    },
    {
      "diary_date": "2026-08-06",
      "meal_type": "breakfast",
      "calories_kcal": 378.0,
      "protein_g": 20.9,
      "fat_g": 16.6,
      "carbs_g": 39.2,
      "foods": "2 небольших варёных яйца • Овощной салат без заправки с мини-моцареллой • Банан"
    },
    {
      "diary_date": "2026-08-06",
      "meal_type": "dinner",
      "calories_kcal": 642.0,
      "protein_g": 50.5,
      "fat_g": 30.5,
      "carbs_g": 41.6,
      "foods": "Лосось; руккола без заправки; стручковая фасоль; голубика"
    },
    {
      "diary_date": "2026-08-06",
      "meal_type": "lunch",
      "calories_kcal": 735.0,
      "protein_g": 42.0,
      "fat_g": 19.0,
      "carbs_g": 97.0,
      "foods": "Макароны-ракушки; филе куриного бедра на пару; салат «Табуле» с запечёнными овощами; морковь и сельдерей"
    },
    {
      "diary_date": "2026-08-06",
      "meal_type": "snack",
      "calories_kcal": 200.0,
      "protein_g": 1.6,
      "fat_g": 0.8,
      "carbs_g": 52.0,
      "foods": "Яблоко; банан"
    },
    {
      "diary_date": "2026-08-07",
      "meal_type": "breakfast",
      "calories_kcal": 324.0,
      "protein_g": 16.2,
      "fat_g": 11.6,
      "carbs_g": 42.1,
      "foods": "2 варёных яйца • Овощи без указанной заправки: помидор, сладкий перец, огурец и листья салата • Банан"
    },
    {
      "diary_date": "2026-08-07",
      "meal_type": "dinner",
      "calories_kcal": 330.0,
      "protein_g": 17.0,
      "fat_g": 24.0,
      "carbs_g": 16.0,
      "foods": "Салат «Цезарь» с креветками и заправкой «Оливковое масло» из «Вкусно — и точка»"
    },
    {
      "diary_date": "2026-08-07",
      "meal_type": "lunch",
      "calories_kcal": 646.0,
      "protein_g": 39.5,
      "fat_g": 22.3,
      "carbs_g": 74.4,
      "foods": "Овощной салат без указанной заправки; картофельное пюре; 2 тефтели из щуки на пару; картофельный суп с куриными фрикадельками"
    },
    {
      "diary_date": "2026-08-07",
      "meal_type": "snack",
      "calories_kcal": 330.0,
      "protein_g": 18.7,
      "fat_g": 1.8,
      "carbs_g": 64.5,
      "foods": "Яблоко • 1,5 ржаных хлебца с консервированным тунцом; киви; маленькая груша"
    },
    {
      "diary_date": "2026-08-08",
      "meal_type": "breakfast",
      "calories_kcal": 771.0,
      "protein_g": 50.8,
      "fat_g": 37.5,
      "carbs_g": 58.3,
      "foods": "Яичница из 2 яиц; мини-салат из помидора и огурца; 2 ржаных хлебца с тунцом; небольшая груша; 3 кусочка сыра маасдам • Киви"
    }
  ],
  "workouts": [
    {
      "diary_date": "2026-08-04",
      "workout_type": "running",
      "duration_minutes": 30.0,
      "distance_km": 5.15,
      "average_pace_seconds_per_km": 350,
      "calories_burned_kcal": null
    },
    {
      "diary_date": "2026-08-05",
      "workout_type": "functional_strength_training",
      "duration_minutes": 48.0,
      "distance_km": null,
      "average_pace_seconds_per_km": null,
      "calories_burned_kcal": 355.0
    },
    {
      "diary_date": "2026-08-06",
      "workout_type": "running",
      "duration_minutes": 30.0,
      "distance_km": 5.52,
      "average_pace_seconds_per_km": 326,
      "calories_burned_kcal": null
    },
    {
      "diary_date": "2026-08-07",
      "workout_type": "running",
      "duration_minutes": 31.0,
      "distance_km": 5.7,
      "average_pace_seconds_per_km": 326,
      "calories_burned_kcal": null
    }
  ],
  "food_bases": [
    {
      "base_type": "chicken",
      "day_count": 4
    },
    {
      "base_type": "fish",
      "day_count": 5
    }
  ],
  "quality": [
    {
      "diary_month": "2026-08",
      "nutrition_entries": 23,
      "estimated_entries": 18,
      "incomplete_macro_entries": 1
    }
  ]
};
